# Define os serviços e volumes que serão usados no Docker Compose

services:
  # Serviço para o banco de dados PostgreSQL
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${WSRS_DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${WSRS_DATABASE_USER}
      POSTGRES_PASSWORD: ${WSRS_DATABASE_PASSWORD}
      POSTGRES_DB: ${WSRS_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data

  # Serviço para o PgAdmin (interface gráfica para gerenciar o PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin

  # Serviço do servidor Go (wsrs)
  wsrs:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      WSRS_DATABASE_PORT: ${WSRS_DATABASE_PORT}
      WSRS_DATABASE_NAME: ${WSRS_DATABASE_NAME}
      WSRS_DATABASE_USER: ${WSRS_DATABASE_USER}
      WSRS_DATABASE_PASSWORD: ${WSRS_DATABASE_PASSWORD}
      WSRS_DATABASE_HOST: db
    ports:
      - 8080:8080 # ou outra porta se desejar
    command: ["./entrypoint.sh"]
    volumes:
      - .:/app
    working_dir: /app

# Define volumes para persistência de dados
volumes:
  db:
    driver: local
  pgadmin:
    driver: local
